echo ********************Generate SMT CFE END********************
cp ../../defaultcfg/100AAVM_TE.rom ./100AAVM_TE.rom
./CompressConfig_CFE ./100AAVM_TE.rom ./100AAVM_TE.rom_COMP
cat ./cfe63268nand128.bm ./100AAVM_TE.rom_COMP > ./cfe63268nand128.tmp
./createboot --boardid=963168MBV_17A --numbermac=4 --macaddr=40:4A:03:00:00:01 --countrycode=FF --manufactureConfig=1 --modelid=6008 --tp=0 --psisize=128 --backuppsi=y --inputfile=cfe63268nand128.tmp --outputfile=cfe63268nand128_Release_TE.bin --cfeSize=$(find . -name cfe63268nand128.bm -printf '%s')
./createboot --boardid=963168MBV_17A --numbermac=4 --macaddr=40:4A:03:00:00:01 --countrycode=FF --manufactureConfig=1 --modelid=6008 --tp=0 --psisize=128 --empty --backuppsi=y --inputfile=cfe63268nand128.tmp --outputfile=cfe63268nand128_TE.bin --cfeSize=$(find . -name cfe63268nand128.bm -printf '%s')
echo ********************Generate SMT CFE END********************
echo ********************Generate SMT file BEGIN********************
./CompressConfig_RAS ./100AAVM.rom ./100AAVM.rom_COMP
./bcmZyNandImageBuilder --output bcmDSL-491GNU-B1B_CTLK_cfe_fs_kernel_NAND128_TE --chip 63268 --board 963168MBV_17A --internalversion="1.00(AAVM.1)b3" --externalversion="CZW002-4.12.009.0" --modelid=6008 --cmodelid=6008 --cfefile cfe63268nand128_TE.bin --rootfsfile rootfs128kb.img --kernelfile vmlinux.lz --include-cfe
./createZyNandimg --boardid=963168MBV_17A --voiceboardid= --numbermac=4 --macaddr=40:4A:03:00:00:01 --countrycode=FF --tp=0 --psisize=128 --gponsn= --gponpw= --backuppsi=y --inputfile=bcmDSL-491GNU-B1B_CTLK_cfe_fs_kernel_NAND128_TE --outputfile=bcmDSL-491GNU-B1B_CTLK_flash_image_963168MBV_17A_NAND128_TE
./NANDimg_gen -v "CZW002-4.12.009.0" -q 1 -t large -M 1
./NANDimg_gen -f bcmDSL-491GNU-B1B_CTLK_flash_image_963168MBV_17A_NAND128_TE -v "CZW002-4.12.009.0" -i 170620_1204 -S 0 -s jffs2 -c on -q 1 -p 128 -t large -o brcom -e 512 -G 50
cat common_header.img partition_header.img > product_header.img
cat product_header.img partition_image.img > bcmDSL-491GNU-B1B_CTLK_SMT_963168MBV_17A_NAND128
echo ********************Generate SMT file END********************
echo ********************Compare SMT file Begin********************
if [ "$(diff ./bcmDSL-491GNU-B1B_CTLK_SMT_963168MBV_17A_NAND128 ../bcmDSL-491GNU-B1B_CTLK_SMT_963168MBV_17A_NAND128)" = "" ]; then
echo -e "\033[32mThe SMT file ./bcmDSL-491GNU-B1B_CTLK_SMT_963168MBV_17A_NAND128 generated by GenSMT.sh is same as ../bcmDSL-491GNU-B1B_CTLK_SMT_963168MBV_17A_NAND128\033[0m"
else
echo -e "\033[33mThe SMT file ./bcmDSL-491GNU-B1B_CTLK_SMT_963168MBV_17A_NAND128 generated by GenSMT.sh is different as ../bcmDSL-491GNU-B1B_CTLK_SMT_963168MBV_17A_NAND128\033[0m"
fi
echo ********************Compare SMT file END********************
