
extern void ip6t_ah_init(void);
extern void ip6t_dst_init(void);
extern void ip6t_eui64_init(void);
extern void ip6t_frag_init(void);
extern void ip6t_hbh_init(void);
extern void ip6t_hl_init(void);
extern void ip6t_icmp6_init(void);
extern void ip6t_ipv6header_init(void);
extern void ip6t_mh_init(void);
extern void ip6t_owner_init(void);
extern void ip6t_policy_init(void);
extern void ip6t_rt_init(void);
extern void ip6t_HL_init(void);
extern void ip6t_LOG_init(void);
extern void ip6t_REJECT_init(void);
extern void xt_TCPMSS_init(void);
extern void xt_SKIPLOG_init(void);
extern void xt_limit_init(void);
extern void xt_standard_init(void);
extern void xt_state_init(void);
extern void xt_tcp_init(void);
extern void xt_udp_init(void);
extern void xt_NFQUEUE_init(void);
extern void xt_dscp_init(void);
extern void xt_DSCP_init(void);
extern void xt_mac_init(void);
extern void xt_mark_init(void);
extern void xt_MARK_init(void);
extern void xt_policer_init(void);
extern void xt_length_init(void);
void init_extensions(void) {
	ip6t_ah_init();
	ip6t_dst_init();
	ip6t_eui64_init();
	ip6t_frag_init();
	ip6t_hbh_init();
	ip6t_hl_init();
	ip6t_icmp6_init();
	ip6t_ipv6header_init();
	ip6t_mh_init();
	ip6t_owner_init();
	ip6t_policy_init();
	ip6t_rt_init();
	ip6t_HL_init();
	ip6t_LOG_init();
	ip6t_REJECT_init();
	xt_TCPMSS_init();
	xt_SKIPLOG_init();
	xt_limit_init();
	xt_standard_init();
	xt_state_init();
	xt_tcp_init();
	xt_udp_init();
	xt_NFQUEUE_init();
	xt_dscp_init();
	xt_DSCP_init();
	xt_mac_init();
	xt_mark_init();
	xt_MARK_init();
	xt_policer_init();
	xt_length_init();
}
