#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "/opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/bin/mips-linux-uclibc-gcc -fPIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DOPENSSL_NO_KRB5 -DOPENSSL_NO_HW -DB_ENDIAN -Os -fomit-frame-pointer -Wall -DOPENSSL_NO_IDEA -DOPENSSL_NO_BF -DOPENSSL_NO_CAST -DOPENSSL_NO_MD2 -DOPENSSL_NO_MD4 -DOPENSSL_NO_RIPEMD -DOPENSSL_NO_MDC2 -DOPENSSL_NO_RC2 -DOPENSSL_NO_DSA -DOPENSSL_NO_EC  -DOPENSSL_NO_ECDH -DOPENSSL_NO_ECDSA -Werror=return-type -Werror=uninitialized -Werror=frame-larger-than=1024 -Wl,-rpath, -L/home/brandon/consume/CZW002-4.12.009.0/targets/DSL-491GNU-B1B_CTLK/fs.install/lib -L/home/brandon/consume/CZW002-4.12.009.0/targets/DSL-491GNU-B1B_CTLK/fs.install/lib/public -I/opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include -Wl,-L/opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/lib -Wl,-L/opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/lib"
  #define PLATFORM "linux-mips"
  #define DATE "Tue Jun 20 11:38:48 CDT 2017"
#endif
